CREATE PROC FI_SP_ConsBeneficiario
	@ID         BIGINT = 0,
	@IDCLIENTE  BIGINT = 0
AS
BEGIN
	IF(ISNULL(@ID,0) > 0)
		SELECT ID, NOME, CPF, IDCLIENTE FROM BENEFICIARIOS WITH(NOLOCK) WHERE ID = @ID
	ELSE IF(ISNULL(@IDCLIENTE,0) > 0)
		SELECT ID, NOME, CPF, IDCLIENTE FROM BENEFICIARIOS WITH(NOLOCK) WHERE IDCLIENTE = @IDCLIENTE
	ELSE
		SELECT ID, NOME, CPF, IDCLIENTE FROM BENEFICIARIOS WITH(NOLOCK) 
END